version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: always
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    depends_on:
      mongo:
        condition: service_healthy
    restart: always
    networks:
      - app_net
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./front
    container_name: frontend
    ports:
      - "80:80"
    restart: always
    networks:
      - app_net
    volumes:
      - ./front:/app

volumes:
  mongo_data:

networks:
  app_net:
    driver: bridge
